import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faPaperPlane,
  faArrowDown,
  faArrowUp,
  faArrowRight,
  faArrowLeft,
  faArrowUpRightFromSquare,
  faCircleArrowDown,
  faShieldHalved,
  faBriefcase,
  faGraduationCap,
  faCompassDrafting,
  faPhotoFilm,
  faPalette,
  faServer,
  faCode,
  faLocationDot,
  faEnvelopeOpenText,
  faCopy,
  faCheck,
  faClock,
  faSun,
  faMoon,
  faBars,
  faXmark,
  faEnvelope,
  faFilePdf,
  faImage,
  faDownload,
  faExpand,
  faMagnifyingGlassPlus,
  faVideo,
  faPlay,
} from "@fortawesome/free-solid-svg-icons";
import {
  faGithub,
  faLinkedin,
  faInstagram,
  faTelegram,
  faFacebook,
  faReact,
  faHtml5,
  faCss3Alt,
  faJs,
  faAws,
  faBootstrap,
  faFigma,
  faPhp,
  faLaravel,
  faGoogle,
  faMicrosoft,
} from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { createApp } from "vue";
import App from "./App.vue";
import "aos/dist/aos.css";
import "./assets/styles/main.scss";
import router from "./router";

library.add(
  faPaperPlane,
  faArrowDown,
  faArrowUp,
  faArrowRight,
  faArrowLeft,
  faArrowUpRightFromSquare,
  faCircleArrowDown,
  faShieldHalved,
  faBriefcase,
  faGraduationCap,
  faCompassDrafting,
  faPhotoFilm,
  faPalette,
  faServer,
  faCode,
  faLocationDot,
  faEnvelopeOpenText,
  faCopy,
  faCheck,
  faClock,
  faSun,
  faMoon,
  faBars,
  faXmark,
  faEnvelope,
  faFilePdf,
  faImage,
  faDownload,
  faExpand,
  faMagnifyingGlassPlus,
  faVideo,
  faPlay,
  faGithub,
  faLinkedin,
  faInstagram,
  faTelegram,
  faFacebook,
  faReact,
  faHtml5,
  faCss3Alt,
  faJs,
  faAws,
  faBootstrap,
  faFigma,
  faPhp,
  faLaravel,
  faGoogle,
  faMicrosoft
);

const app = createApp(App);
app.use(router);
app.component("font-awesome-icon", FontAwesomeIcon);
app.mount("#app");
